apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv-0
  namespace: elastic-system
  labels:
    type: local
spec:
  storageClassName: fast
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/elasticsearch-pv-0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv-1
  namespace: elastic-system
  labels:
    type: local
spec:
  storageClassName: fast
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/elasticsearch-pv-1"
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: elastic-system
spec:
  version: 7.9.0
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: default
      count: 2
      config:
        node.master: true
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                limits:
                  ephemeral-storage: 1Gi
                requests:
                  ephemeral-storage: 500Mi
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 0.5Gi
            storageClassName: fast
---
apiVersion: v1
kind: Service
metadata:
  name: quickstart-es-http
  namespace: elastic-system
  labels:
    app: quickstart-es
spec:
  selector:
    app: quickstart-es
  type: NodePort
  ports:
    - port: 9200
      nodePort: 30200